name: buffered_stream
description: A stream implementation that queues all inputs until there is a listener.
version: 1.0.0
homepage: https://kaaninel.co
authors:
  - "Kaan Inel <kaaninel@gmail.com>"

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
